language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/bbbq


after_script:
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"
  - make clean
  - make data
  - make

